/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.krdb.ssqlt.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
