/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.kotlin-application-conventions") }

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
}

application {
    // Define the main class for the application.
    mainClass = "eu.krdb.ssqlt.app.AppKt"
}
