/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    id("com.ncorti.ktfmt.gradle") version "0.19.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
}

application {
    // Define the main class for the application.
    mainClass = "eu.krdb.ssqlt.app.AppKt"
}

ktfmt {
    kotlinLangStyle()
}
