/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    implementation("org.postgresql:postgresql:42.1.4")
    implementation("io.github.microutils:kotlin-logging-jvm:2.0.11")
}
